### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by albertosdneto** [gustavo0197/dart-jwt-decoder#1]
Hello!
Nice job with the JWT Decoder!
Congrats!

What license do you intend to use at  Dart JWT Decoder?

Please, specify the licence for this package, so we can legally use it.

Thank you for the great job!

PS.: MIT License would be great.

**Comment by gustavo0197** [comment]
Hi, I've just added a MIT license

**Comment by albertosdneto** [comment]
Thank you!
