### ISSUE TITLE
Function to get expiration date and time of token

### ISSUE THREAD

**Issue by madatr** [gustavo0197/dart-jwt-decoder#2]
Hi Mr. Velazquez,

Thank you for the useful plugin.

I was wondering if you are able to implement a function to just get the expiration date and time of the token.

The function provided probably does the check using this information anyway, it's just a matter of exposing it.

I will be using it to check whether the employee's token is going to be expiring soon so that i'd refresh it as I wont be running the check often.

Thanks again,

**Comment by gustavo0197** [comment]
Hi! yes, I can implement that function, in a couple of days it'll be ready

**Comment by gustavo0197** [comment]
I just added 2 new functions 🤘

**Comment by madatr** [comment]
Super! Thank you very much for the fast action Mr  Velazquez
